### ISSUE TITLE
Can't access local VoSeq

### ISSUE THREAD

**Issue by kevinliam** [VoSeq/VoSeq#354]
Hi Carlos,

In trying to fix the search function for my VoSeq installation I have made things much worse. Now when entering http://33.33.33.10/ into my web browser I am taken to a page that says "Welcome to nginx!". Do you have any ideas on how to fix the situation? I'm fine with uninstalling completely and reinstalling. I'm running Ubuntu 14.04.

Kevin
![screenshot from 2016-09-27 19 09 06](https://cloud.githubusercontent.com/assets/19877238/18895313/a6a30774-84e6-11e6-9b58-f13ee7ad7ad0.png)

**Comment by kevinliam** [comment]
Problem solved by clearing my web browser's cache!

**Comment by carlosp420** [comment]
great!
