### ISSUE TITLE
make migrations fails due to error: debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE_CLASSES.

### ISSUE THREAD

**Issue by kevinliam** [VoSeq/VoSeq#360]
Hey Carlos,

When installing VoSeq locally on my Ubuntu 16.04 machine the installation would fail at the `make migrations` step. I fixed the issue by adding the line `debug_toolbar.middleware.DebugToolbarMiddleware` to the MIDDLEWARE_CLASSES section in base.py in ~VoSeq/voseq/voseq/settings

Kevin

**Comment by carlosp420** [comment]
thanks!
