### ISSUE TITLE
Issue with Google Maps API key 

### ISSUE THREAD

**Issue by vatese** [VoSeq/VoSeq#361]
Hello!

Just to let you know the API key for google maps is wonky:

Google Maps API error: InvalidKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key-map-error
_.kb @ js?key=get_a_google_map_api_key:33

Cheers,

**Comment by carlosp420** [comment]
yes the default installation comes with:
```
"GOOGLE_MAPS_API_KEY": "get_a_google_map_api_key",
``` :-D

**Comment by vatese** [comment]
Woops, my bad for not looking further. I was a little naive to assume it will come with a valid API key. I placed a new one.

Cheers and thanks,
