### ISSUE TITLE
allow taxon names in fasta file to be longer than 54 characters

### ISSUE THREAD

**Issue by mariespe** [VoSeq/VoSeq#388]
When I make a dataset the taxon names in the fasta file are automatically cut off if they are longer than 54 characters. Would it be possible to allow for longer names?

**Comment by carlosp420** [comment]
fixed with #396 
<img width="1063" alt="Screen Shot 2020-06-28 at 16 44 43" src="https://user-images.githubusercontent.com/710117/85959182-6f170500-b960-11ea-80b6-1de2b16bbb99.png">
